Update Renice.cpp
Trying to fix error:

bin/renice/Renice.cpp:1:10: fatal error: sys/renice.h: No such file or directory
    1 | #include "sys/renice.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
scons: *** [build/intel/pc/bin/renice/Renice.o] Error 1
scons: building terminated because of errors.